# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Auto-generated Dockerfile for MCP Training
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json .
RUN npm install

# Copy TypeScript config and source code
COPY tsconfig.json .
COPY src ./src

# Build the project
RUN npm run build

# Default command to run the MCP server over stdio
CMD ["node", "dist/index.js"]
